/**
 * This file is auto-generated by scripts/sync-api.ts
 * Do not edit manually. Run `npm run sync-api` to regenerate.
 *
 * Generated from: https://vloct-dev--chatterbox-tts-chatterbox-serve.modal.run/openapi.json
 * Generated at: 2026-03-25T23:10:36.913Z
 */
export interface paths {
  "/generate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate Speech */
    post: operations["generate_speech_generate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * TTSRequest
     * @description Request model for text-to-speech generation.
     */
    TTSRequest: {
      /** Prompt */
      prompt: string;
      /** Voice Key */
      voice_key: string;
      /**
       * Language Id
       * @default en
       */
      language_id: string;
      /**
       * Temperature
       * @default 0.8
       */
      temperature: number;
      /**
       * Exaggeration
       * @default 0.5
       */
      exaggeration: number;
      /**
       * Cfg Weight
       * @default 0.5
       */
      cfg_weight: number;
      /**
       * Norm Loudness
       * @default true
       */
      norm_loudness: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  generate_speech_generate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TTSRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
          "audio/wav": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
